version: '3'
services:
  vectordatabase:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - 6333:6333
  clipasservice:
    image: supervisely/cas_tensorrt
    container_name: castensorrt
    ports:
      - 51000:51000