FROM nvcr.io/nvidia/tensorrt:24.04-py3

RUN pip3 install --default-timeout=1000 --no-cache-dir torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu121
RUN python3 -m pip install --no-cache-dir "clip-server[tensorrt]"

CMD ["python3", "-m", "clip_server"]